version: '3'

services: 
    reverse_proxy:
        image: nginx:latest
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - "80:80"
        depends_on: 
            - web
    
    web:
        build: ./webapp
        ports: 
            - "3000:3000"
        depends_on: 
            - api
    
    api:
        build: ./backend
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - "8000:8000"
        depends_on: 
            - db
    
    db:
        image: postgres
        volumes: 
            - ./data/db:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres